# Generated by Django 5.0.2 on 2024-02-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshareapi', '0003_sharedpermission_book_shared_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedpermission',
            name='user',
        ),
    ]
