# Generated by Django 5.0.2 on 2024-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshareapi', '0004_remove_sharedpermission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='shared_permissions',
            field=models.ManyToManyField(blank=True, related_name='books_shared_permission', to='bookshareapi.sharedpermission'),
        ),
    ]
